
#        0: "HHPHHHPH"
#        1: "HHPHHHPHPHHHPH"
#        2: "HPHPPHHPHPPHPHHPPHPH"
#        3: "PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP"
#        4: "HHPHPHPHPHHHHPHPPPHPPPHPPPPHPPPHPPPHPHHHHPHPHPHPHH" 
#        5: "PPCHHPPCHPPPPCHHHHCHHPPHHPPPPHHPPHPP"
#        6: "CPPCHPPCHPPCPPHHHHHHCCPCHPPCPCHPPHPC"
#        7: "HCPHPCPHPCHCHPHPPPHPPPHPPPPHPCPHPPPHPHHHCCHCHCHCHH" 
#        8: "HCPHPHPHCHHHHPCCPPHPPPHPPPPCPPPHPPPHPHHHHCHPHPHPHH"

list = ["HHPHHHPH", 
         "HHPHHHPHPHHHPH", 
         "HPHPPHHPHPPHPHHPPHPH", 
         "PPPHHPPHHPPPPPHHHHHHHPPHHPPPPHHPPHPP", 
         "HHPHPHPHPHHHHPHPPPHPPPHPPPPHPPPHPPPHPHHHHPHPHPHPHH", 
         "PPCHHPPCHPPPPCHHHHCHHPPHHPPPPHHPPHPP", 
         "CPPCHPPCHPPCPPHHHHHHCCPCHPPCPCHPPHPC", 
         "HCPHPCPHPCHCHPHPPPHPPPHPPPPHPCPHPPPHPHHHCCHCHCHCHH", 
         "HCPHPHPHCHHHHPCCPPHPPPHPPPPCPPPHPPPHPHHHHCHPHPHPHH"]
